
variable "subscription_id" {
  description = "Azure Subscription ID"
  sensitive   = false
  nullable    = false
  type        = string
}

variable "location" {
  description = "Azure Location"
  sensitive   = false
  nullable    = false
  type        = string
  default     = "East US"
}

variable "storage_account_name" {
  description = "Storage account name (must be 3-11 lowercase alphanumeric characters)"
  sensitive   = false
  nullable    = false
  type        = string
  default     = "mixosvhd"
  validation {
    condition     = can(regex("^[a-z0-9]{3,11}$", var.storage_account_name))
    error_message = "storage_account_name must contain 3-11 lowercase alphanumeric characters."
  }
}

variable "vhd_absolute_path" {
  description = "Absolute path to the VHD file generated by Nix that should be uploaded"
  sensitive   = false
  nullable    = false
  type        = string
  validation {
    condition     = can(regex("\\.vhd$", lower(var.vhd_absolute_path)))
    error_message = "vhd_absolute_path must point to a file with a .vhd extension."
  }
}

variable "vhd_blob_name" {
  description = "Name to use for the uploaded VHD blob"
  sensitive   = false
  nullable    = false
  type        = string
  default     = "mixos-remote-builder.vhd"
}

variable "image_name" {
  description = "Name for the Azure managed image created from the VHD"
  sensitive   = false
  nullable    = false
  type        = string
  default     = "mixos-remote-builder-image"
}

variable "image_hyper_v_generation" {
  description = "Hyper-V generation of the image (V1 for BIOS/legacy VHDs, V2 for UEFI VHDs)"
  sensitive   = false
  nullable    = false
  type        = string
  default     = "V2"
  validation {
    condition     = contains(["V1", "V2"], var.image_hyper_v_generation)
    error_message = "image_hyper_v_generation must be either V1 or V2."
  }
}
